# Generated by Django 5.1.15 on 2026-08-23 21:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_terms', models.BooleanField(help_text='Términos y condiciones aceptados al enviar el formulario.')),
                ('confirmed_eligibility', models.BooleanField(help_text='Confirmación de que todos los integrantes cursan un programa de educación superior en el Valle de Aburrá.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Slot 1-6 tal como aparece en el formulario (1 = representante del grupo).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_leader', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('document_id', models.CharField(max_length=50, verbose_name='Documento de identidad')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución de educación superior')),
                ('institutional_email', models.EmailField(max_length=254, verbose_name='Correo institucional')),
                ('phone', models.CharField(max_length=30, verbose_name='Celular')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='registrations.registration')),
            ],
            options={
                'ordering': ['registration_id', 'position'],
                'constraints': [models.UniqueConstraint(fields=('registration', 'position'), name='unique_position_per_registration')],
            },
        ),
    ]
