# Generated by Django 5.1.15 on 2026-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Se llena solo cuando el envío del correo de confirmación tuvo éxito (nunca al momento de intentarlo) — permite reintentar envíos masivos sin duplicar correos a quien ya lo recibió.', null=True),
        ),
    ]
