# Generated by Django 5.1.15 on 2026-10-06 00:36

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_confirmation_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('document_id', models.CharField(max_length=50, verbose_name='Documento de identidad')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=30, verbose_name='Celular')),
                ('accepted_terms', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_talk_registration_email')],
            },
        ),
    ]
